import 'package:design_system/design_system.dart';
import 'package:design_system/src/extensions/shad_ext.dart';
import 'package:shadcn_ui/shadcn_ui.dart';

class DsInputDatePicker extends ShadDatePicker {
  /// Creates a single-date picker widget with a button and popover calendar.
  DsInputDatePicker({
    super.key,
    super.placeholder,
    super.popoverController,
    super.selected,
    super.closeOnSelection,
    String Function(DateTime)? formatDate,
    super.allowDeselection,
    super.header,
    super.footer,
    super.groupId,
    super.calendarDecoration,
    super.popoverPadding,
    super.multipleSelected,
    super.onChanged,
    super.onMultipleChanged,
    super.showOutsideDays,
    super.initialMonth,
    super.formatMonthYear,
    super.formatMonth,
    super.formatYear,
    super.formatWeekday,
    super.showWeekNumbers,
    super.weekStartsOn,
    super.fixedWeeks,
    super.hideWeekdayNames,
    super.numberOfMonths = 1,
    super.fromMonth,
    super.toMonth,
    super.onMonthChanged,
    super.reverseMonths = false,
    super.min,
    super.max,
    super.selectableDayPredicate,
    super.onRangeChanged,
    super.captionLayout,
    super.hideNavigation,
    super.yearSelectorMinWidth,
    super.monthSelectorMinWidth,
    super.yearSelectorPadding,
    super.monthSelectorPadding,
    super.navigationButtonSize,
    super.navigationButtonIconSize,
    super.backNavigationButtonIconData,
    super.forwardNavigationButtonIconData,
    super.navigationButtonPadding,
    super.navigationButtonDisabledOpacity,
    super.decoration,
    super.spacingBetweenMonths,
    super.runSpacingBetweenMonths,
    super.monthConstraints,
    super.calendarHeaderHeight,
    super.calendarHeaderPadding,
    super.captionLayoutGap,
    super.calendarHeaderTextStyle,
    super.weekdaysPadding,
    super.weekdaysTextStyle,
    super.weekdaysTextAlign,
    super.weekNumbersHeaderText,
    super.weekNumbersHeaderTextStyle,
    super.weekNumbersTextStyle,
    super.weekNumbersTextAlign,
    super.dayButtonSize,
    super.dayButtonOutsideMonthOpacity,
    super.dayButtonPadding,
    super.dayButtonDecoration,
    super.selectedDayButtonTextStyle,
    super.insideRangeDayButtonTextStyle,
    super.dayButtonTextStyle,
    super.dayButtonVariant,
    super.selectedDayButtonVariant,
    super.insideRangeDayButtonVariant,
    super.todayButtonVariant,
    super.gridMainAxisSpacing,
    super.gridCrossAxisSpacing,
    super.dayButtonOutsideMonthTextStyle,
    super.dayButtonOutsideMonthVariant,
    super.selectedDayButtonOusideMonthVariant,
    super.closeOnTapOutside = true,
    super.focusNode,
    super.anchor,
    super.effects,
    super.shadows,
    super.popoverDecoration,
    super.filter,
    super.areaGroupId,
    super.useSameGroupIdForChild = true,
    super.onPressed,
    super.onLongPress,
    super.icon,
    super.buttonChild,
    super.buttonVariant,
    super.size,
    super.cursor,
    super.width,
    super.height,
    super.buttonPadding,
    super.backgroundColor,
    super.hoverBackgroundColor,
    super.foregroundColor,
    super.hoverForegroundColor,
    super.autofocus = false,
    super.buttonFocusNode,
    super.pressedBackgroundColor,
    super.pressedForegroundColor,
    super.buttonShadows,
    super.gradient,
    super.textDecoration,
    super.hoverTextDecoration,
    super.buttonDecoration,
    super.enabled = true,
    super.statesController,
    super.gap,
    super.mainAxisAlignment,
    super.crossAxisAlignment,
    super.hoverStrategies,
    super.onHoverChange,
    super.onTapDown,
    super.onTapUp,
    super.onTapCancel,
    super.onSecondaryTapDown,
    super.onSecondaryTapUp,
    super.onSecondaryTapCancel,
    super.onLongPressStart,
    super.onLongPressCancel,
    super.onLongPressUp,
    super.onLongPressDown,
    super.onLongPressEnd,
    super.onDoubleTap,
    super.onDoubleTapDown,
    super.onDoubleTapCancel,
    super.longPressDuration,
    super.textDirection,
    super.onFocusChange,
    super.iconData,
    super.orderPolicy,
    super.expands,
  }) : super(formatDate: formatDate ?? (date) => date.formatDateToPtBr);

  /// Creates a date range picker widget with a button and popover calendar.
  DsInputDatePicker.range({
    super.key,
    super.popoverController,
    super.placeholder,
    ShadDateTimeRange? selected,
    String Function(DSDateTimeRange)? formatDateRange,
    super.closeOnSelection,
    super.allowDeselection,
    super.header,
    super.footer,
    super.groupId,
    super.calendarDecoration,
    super.popoverPadding,
    super.multipleSelected,
    super.onChanged,
    super.onMultipleChanged,
    super.showOutsideDays,
    super.initialMonth,
    super.formatMonthYear,
    super.formatMonth,
    super.formatYear,
    super.formatWeekday,
    super.showWeekNumbers,
    super.weekStartsOn,
    super.fixedWeeks,
    super.hideWeekdayNames,
    super.numberOfMonths = 1,
    super.fromMonth,
    super.toMonth,
    super.onMonthChanged,
    super.reverseMonths = false,
    super.min,
    super.max,
    super.selectableDayPredicate,
    super.onRangeChanged,
    super.captionLayout,
    super.hideNavigation,
    super.yearSelectorMinWidth,
    super.monthSelectorMinWidth,
    super.yearSelectorPadding,
    super.monthSelectorPadding,
    super.navigationButtonSize,
    super.navigationButtonIconSize,
    super.backNavigationButtonIconData,
    super.forwardNavigationButtonIconData,
    super.navigationButtonPadding,
    super.navigationButtonDisabledOpacity,
    super.decoration,
    super.spacingBetweenMonths,
    super.runSpacingBetweenMonths,
    super.monthConstraints,
    super.calendarHeaderHeight,
    super.calendarHeaderPadding,
    super.captionLayoutGap,
    super.calendarHeaderTextStyle,
    super.weekdaysPadding,
    super.weekdaysTextStyle,
    super.weekdaysTextAlign,
    super.weekNumbersHeaderText,
    super.weekNumbersHeaderTextStyle,
    super.weekNumbersTextStyle,
    super.weekNumbersTextAlign,
    super.dayButtonSize,
    super.dayButtonOutsideMonthOpacity,
    super.dayButtonPadding,
    super.dayButtonDecoration,
    super.selectedDayButtonTextStyle,
    super.insideRangeDayButtonTextStyle,
    super.dayButtonTextStyle,
    super.dayButtonVariant,
    super.selectedDayButtonVariant,
    super.insideRangeDayButtonVariant,
    super.todayButtonVariant,
    super.gridMainAxisSpacing,
    super.gridCrossAxisSpacing,
    super.dayButtonOutsideMonthTextStyle,
    super.dayButtonOutsideMonthVariant,
    super.selectedDayButtonOusideMonthVariant,
    super.closeOnTapOutside = true,
    super.focusNode,
    super.anchor,
    super.effects,
    super.shadows,
    super.popoverDecoration,
    super.filter,
    super.areaGroupId,
    super.useSameGroupIdForChild = true,
    super.onPressed,
    super.onLongPress,
    super.icon,
    super.buttonChild,
    super.buttonVariant,
    super.size,
    super.cursor,
    super.width,
    super.height,
    super.buttonPadding,
    super.backgroundColor,
    super.hoverBackgroundColor,
    super.foregroundColor,
    super.hoverForegroundColor,
    super.autofocus = false,
    super.buttonFocusNode,
    super.pressedBackgroundColor,
    super.pressedForegroundColor,
    super.buttonShadows,
    super.gradient,
    super.textDecoration,
    super.hoverTextDecoration,
    super.buttonDecoration,
    super.enabled = true,
    super.statesController,
    super.gap,
    super.mainAxisAlignment,
    super.crossAxisAlignment,
    super.hoverStrategies,
    super.onHoverChange,
    super.onTapDown,
    super.onTapUp,
    super.onTapCancel,
    super.onSecondaryTapDown,
    super.onSecondaryTapUp,
    super.onSecondaryTapCancel,
    super.onLongPressStart,
    super.onLongPressCancel,
    super.onLongPressUp,
    super.onLongPressDown,
    super.onLongPressEnd,
    super.onDoubleTap,
    super.onDoubleTapDown,
    super.onDoubleTapCancel,
    super.longPressDuration,
    super.textDirection,
    super.onFocusChange,
    super.iconData,
    super.orderPolicy,
    super.expands,
  }) : super.range(
            formatDateRange: formatDateRange != null
                ? (date) => formatDateRange(
                    DSDateTimeRange(start: date.start, end: date.end))
                : (date) => date.formatDateRangeToPtBr);

  /// Creates a date picker widget with a specified [variant], offering full
  /// customization.
  DsInputDatePicker.raw({
    super.key,
    required super.variant,
    super.popoverController,
    super.selected,
    super.closeOnSelection,
    String Function(DateTime)? formatDate,
    super.allowDeselection,
    super.selectedRange,
    super.header,
    super.footer,
    super.groupId,
    super.calendarDecoration,
    super.popoverPadding,
    super.multipleSelected,
    super.onChanged,
    super.onMultipleChanged,
    super.showOutsideDays,
    super.initialMonth,
    super.formatMonthYear,
    super.formatMonth,
    super.formatYear,
    super.formatWeekday,
    super.showWeekNumbers,
    super.weekStartsOn,
    super.fixedWeeks,
    super.hideWeekdayNames,
    super.numberOfMonths = 1,
    super.fromMonth,
    super.toMonth,
    super.onMonthChanged,
    super.reverseMonths = false,
    super.min,
    super.max,
    super.selectableDayPredicate,
    super.onRangeChanged,
    super.captionLayout,
    super.hideNavigation,
    super.yearSelectorMinWidth,
    super.monthSelectorMinWidth,
    super.yearSelectorPadding,
    super.monthSelectorPadding,
    super.navigationButtonSize,
    super.navigationButtonIconSize,
    super.backNavigationButtonIconData,
    super.forwardNavigationButtonIconData,
    super.navigationButtonPadding,
    super.navigationButtonDisabledOpacity,
    super.decoration,
    super.spacingBetweenMonths,
    super.runSpacingBetweenMonths,
    super.monthConstraints,
    super.calendarHeaderHeight,
    super.calendarHeaderPadding,
    super.captionLayoutGap,
    super.calendarHeaderTextStyle,
    super.weekdaysPadding,
    super.weekdaysTextStyle,
    super.weekdaysTextAlign,
    super.weekNumbersHeaderText,
    super.weekNumbersHeaderTextStyle,
    super.weekNumbersTextStyle,
    super.weekNumbersTextAlign,
    super.dayButtonSize,
    super.dayButtonOutsideMonthOpacity,
    super.dayButtonPadding,
    super.dayButtonDecoration,
    super.selectedDayButtonTextStyle,
    super.insideRangeDayButtonTextStyle,
    super.dayButtonTextStyle,
    super.dayButtonVariant,
    super.selectedDayButtonVariant,
    super.insideRangeDayButtonVariant,
    super.todayButtonVariant,
    super.gridMainAxisSpacing,
    super.gridCrossAxisSpacing,
    super.dayButtonOutsideMonthTextStyle,
    super.dayButtonOutsideMonthVariant,
    super.selectedDayButtonOusideMonthVariant,
    super.closeOnTapOutside = true,
    super.focusNode,
    super.anchor,
    super.effects,
    super.shadows,
    super.popoverDecoration,
    super.filter,
    super.areaGroupId,
    super.useSameGroupIdForChild = true,
    super.onPressed,
    super.onLongPress,
    super.icon,
    super.buttonChild,
    super.buttonVariant,
    super.size,
    super.cursor,
    super.width,
    super.height,
    super.buttonPadding,
    super.backgroundColor,
    super.hoverBackgroundColor,
    super.foregroundColor,
    super.hoverForegroundColor,
    super.autofocus = false,
    super.buttonFocusNode,
    super.pressedBackgroundColor,
    super.pressedForegroundColor,
    super.buttonShadows,
    super.gradient,
    super.textDecoration,
    super.hoverTextDecoration,
    super.buttonDecoration,
    super.enabled = true,
    super.statesController,
    super.gap,
    super.mainAxisAlignment,
    super.crossAxisAlignment,
    super.hoverStrategies,
    super.onHoverChange,
    super.onTapDown,
    super.onTapUp,
    super.onTapCancel,
    super.onSecondaryTapDown,
    super.onSecondaryTapUp,
    super.onSecondaryTapCancel,
    super.onLongPressStart,
    super.onLongPressCancel,
    super.onLongPressUp,
    super.onLongPressDown,
    super.onLongPressEnd,
    super.onDoubleTap,
    super.onDoubleTapDown,
    super.onDoubleTapCancel,
    super.longPressDuration,
    super.textDirection,
    super.onFocusChange,
    super.iconData,
    String Function(DateTime)? formatDateRange,
    super.placeholder,
    super.orderPolicy,
    super.expands,
  }) : super.raw(
          formatDate: formatDate ?? (date) => date.formatDateToPtBr,
        );
}
