import 'package:design_system/src/widgets/calendar/enums/ds_calendar_enum.dart';
import 'package:design_system/src/widgets/calendar/models/ds_calendar_model.dart';
import 'package:flutter/material.dart';
import 'package:shadcn_ui/shadcn_ui.dart';

export 'enums/ds_calendar_enum.dart';
export 'models/ds_calendar_model.dart';

/// Um widget de calendário personalizável para selecionar datas ou intervalos de datas.
///
/// O widget [DSCalendar] suporta seleção de uma única data, seleção de múltiplas datas
/// ou seleção de intervalo de datas através de suas variantes. Ele oferece extensa
/// personalização para aparência, navegação e comportamento. Use construtores nomeados como [DSCalendar.multiple]
/// ou [DSCalendar.range] para modos de seleção específicos, ou [DSCalendar.raw]
/// para controle total.
class DSCalendar extends ShadCalendar {
  /// Cria um widget de calendário para seleção de uma única data.
  const DSCalendar({
    super.key,
    super.selected,
    super.onChanged,
    super.showOutsideDays,
    super.initialMonth,
    super.formatMonthYear,
    super.formatMonth,
    super.formatYear,
    super.formatWeekday,
    super.showWeekNumbers,
    super.weekStartsOn,
    super.fixedWeeks,
    super.hideWeekdayNames,
    super.numberOfMonths = 1,
    super.fromMonth,
    super.toMonth,
    super.onMonthChanged,
    super.reverseMonths = false,
    super.selectableDayPredicate,
    DSCalendarCaptionLayout? captionLayout,
    super.hideNavigation,
    super.yearSelectorMinWidth,
    super.monthSelectorMinWidth,
    super.yearSelectorPadding,
    super.monthSelectorPadding,
    super.navigationButtonSize,
    super.navigationButtonIconSize,
    super.backNavigationButtonIconData,
    super.forwardNavigationButtonIconData,
    super.navigationButtonPadding,
    super.navigationButtonDisabledOpacity,
    super.spacingBetweenMonths,
    super.runSpacingBetweenMonths,
    super.monthConstraints,
    super.headerHeight,
    super.headerPadding,
    super.captionLayoutGap,
    super.headerTextStyle,
    super.weekdaysPadding,
    super.weekdaysTextStyle,
    super.weekdaysTextAlign,
    super.weekNumbersHeaderText,
    super.weekNumbersHeaderTextStyle,
    super.weekNumbersTextStyle,
    super.weekNumbersTextAlign,
    super.dayButtonSize,
    super.dayButtonOutsideMonthOpacity,
    super.dayButtonPadding,
    super.dayButtonDecoration,
    super.selectedDayButtonTextStyle,
    super.insideRangeDayButtonTextStyle,
    super.dayButtonTextStyle,
    super.dayButtonVariant,
    super.selectedDayButtonVariant,
    super.insideRangeDayButtonVariant,
    super.todayButtonVariant,
    super.gridMainAxisSpacing,
    super.gridCrossAxisSpacing,
    super.dayButtonOutsideMonthTextStyle,
    super.dayButtonOutsideMonthVariant,
    super.selectedDayButtonOusideMonthVariant,
    super.allowDeselection,
    super.groupId,
  }) : super(
          decoration: const ShadDecoration(),
        );

  /// Cria um widget de calendário para seleção de múltiplas datas.
  DSCalendar.multiple({
    super.key,
    super.showOutsideDays,
    super.initialMonth,
    super.formatMonthYear,
    super.formatMonth,
    super.formatYear,
    super.formatWeekday,
    super.showWeekNumbers,
    super.weekStartsOn,
    super.fixedWeeks,
    super.hideWeekdayNames,
    super.numberOfMonths = 1,
    super.fromMonth,
    super.toMonth,
    super.onMonthChanged,
    super.reverseMonths = false,
    super.min,
    super.max,
    super.selectableDayPredicate,
    DSCalendarCaptionLayout? captionLayout,
    super.hideNavigation,
    super.yearSelectorMinWidth,
    super.monthSelectorMinWidth,
    super.yearSelectorPadding,
    super.monthSelectorPadding,
    super.navigationButtonSize,
    super.navigationButtonIconSize,
    super.backNavigationButtonIconData,
    super.forwardNavigationButtonIconData,
    super.navigationButtonPadding,
    super.navigationButtonDisabledOpacity,
    super.decoration,
    super.spacingBetweenMonths,
    super.runSpacingBetweenMonths,
    super.monthConstraints,
    super.headerHeight,
    super.headerPadding,
    super.captionLayoutGap,
    super.headerTextStyle,
    super.weekdaysPadding,
    super.weekdaysTextStyle,
    super.weekdaysTextAlign,
    super.weekNumbersHeaderText,
    super.weekNumbersHeaderTextStyle,
    super.weekNumbersTextStyle,
    super.weekNumbersTextAlign,
    super.dayButtonSize,
    super.dayButtonOutsideMonthOpacity,
    super.dayButtonPadding,
    super.dayButtonDecoration,
    super.selectedDayButtonTextStyle,
    super.insideRangeDayButtonTextStyle,
    super.dayButtonTextStyle,
    super.dayButtonVariant,
    super.selectedDayButtonVariant,
    super.insideRangeDayButtonVariant,
    super.todayButtonVariant,
    super.gridMainAxisSpacing,
    super.gridCrossAxisSpacing,
    super.dayButtonOutsideMonthTextStyle,
    super.dayButtonOutsideMonthVariant,
    super.selectedDayButtonOusideMonthVariant,
    super.groupId,
  }) : super.multiple(
            captionLayout: captionLayout?.mapToShadCalendarCaptionLayout);

  /// Cria um widget de calendário para seleção de intervalo de datas.
  DSCalendar.range({
    super.key,
    ShadDateTimeRange? selected,
    ValueChanged<ShadDateTimeRange?>? onChanged,
    super.showOutsideDays,
    super.initialMonth,
    super.formatMonthYear,
    super.formatMonth,
    super.formatYear,
    super.formatWeekday,
    super.showWeekNumbers = false,
    super.weekStartsOn,
    super.fixedWeeks,
    super.hideWeekdayNames,
    super.numberOfMonths = 1,
    super.fromMonth,
    super.toMonth,
    super.onMonthChanged,
    super.reverseMonths = false,
    super.min,
    super.max,
    super.selectableDayPredicate,
    DSCalendarCaptionLayout? captionLayout,
    super.hideNavigation,
    super.yearSelectorMinWidth,
    super.monthSelectorMinWidth,
    super.yearSelectorPadding,
    super.monthSelectorPadding,
    super.navigationButtonSize,
    super.navigationButtonIconSize,
    super.backNavigationButtonIconData,
    super.forwardNavigationButtonIconData,
    super.navigationButtonPadding,
    super.navigationButtonDisabledOpacity,
    super.decoration,
    super.spacingBetweenMonths,
    super.runSpacingBetweenMonths,
    super.monthConstraints,
    super.headerHeight,
    super.headerPadding,
    super.captionLayoutGap,
    super.headerTextStyle,
    super.weekdaysPadding,
    super.weekdaysTextStyle,
    super.weekdaysTextAlign,
    super.weekNumbersHeaderText,
    super.weekNumbersHeaderTextStyle,
    super.weekNumbersTextStyle,
    super.weekNumbersTextAlign,
    super.dayButtonSize,
    super.dayButtonOutsideMonthOpacity,
    super.dayButtonPadding,
    super.dayButtonDecoration,
    super.selectedDayButtonTextStyle,
    super.insideRangeDayButtonTextStyle,
    super.dayButtonTextStyle,
    super.dayButtonVariant,
    super.selectedDayButtonVariant,
    super.insideRangeDayButtonVariant,
    super.todayButtonVariant,
    super.gridMainAxisSpacing,
    super.gridCrossAxisSpacing,
    super.dayButtonOutsideMonthTextStyle,
    super.dayButtonOutsideMonthVariant,
    super.selectedDayButtonOusideMonthVariant,
    super.allowDeselection,
    super.groupId,
  }) : super.range(
            captionLayout: captionLayout?.mapToShadCalendarCaptionLayout);

  /// Cria um widget de calendário com um [variant] especificado, permitindo total
  /// personalização.
  DSCalendar.raw({
    super.key,
    required super.variant,
    super.selected,
    super.multipleSelected,
    super.onChanged,
    super.onMultipleChanged,
    super.showOutsideDays,
    super.initialMonth,
    super.formatMonthYear,
    super.formatMonth,
    super.formatYear,
    super.formatWeekday,
    super.showWeekNumbers,
    super.weekStartsOn,
    super.fixedWeeks,
    super.hideWeekdayNames,
    super.numberOfMonths = 1,
    super.fromMonth,
    super.toMonth,
    super.onMonthChanged,
    super.reverseMonths = false,
    super.min,
    super.max,
    super.selectableDayPredicate,
    super.onRangeChanged,
    DSDateTimeRange? selectedRange,
    DSCalendarCaptionLayout? captionLayout,
    super.hideNavigation,
    super.yearSelectorMinWidth,
    super.monthSelectorMinWidth,
    super.yearSelectorPadding,
    super.monthSelectorPadding,
    super.navigationButtonSize,
    super.navigationButtonIconSize,
    super.backNavigationButtonIconData,
    super.forwardNavigationButtonIconData,
    super.navigationButtonPadding,
    super.navigationButtonDisabledOpacity,
    super.decoration,
    super.spacingBetweenMonths,
    super.runSpacingBetweenMonths,
    super.monthConstraints,
    super.headerHeight,
    super.headerPadding,
    super.captionLayoutGap,
    super.headerTextStyle,
    super.weekdaysPadding,
    super.weekdaysTextStyle,
    super.weekdaysTextAlign,
    super.weekNumbersHeaderText,
    super.weekNumbersHeaderTextStyle,
    super.weekNumbersTextStyle,
    super.weekNumbersTextAlign,
    super.dayButtonSize,
    super.dayButtonOutsideMonthOpacity,
    super.dayButtonPadding,
    super.dayButtonDecoration,
    super.selectedDayButtonTextStyle,
    super.insideRangeDayButtonTextStyle,
    super.dayButtonTextStyle,
    super.dayButtonVariant,
    super.selectedDayButtonVariant,
    super.insideRangeDayButtonVariant,
    super.todayButtonVariant,
    super.gridMainAxisSpacing,
    super.gridCrossAxisSpacing,
    super.dayButtonOutsideMonthTextStyle,
    super.dayButtonOutsideMonthVariant,
    super.selectedDayButtonOusideMonthVariant,
    super.allowDeselection,
    super.groupId,
  }) : super.raw(
            selectedRange: selectedRange,
            captionLayout: captionLayout?.mapToShadCalendarCaptionLayout);
}
